### PR TITLE
Fix warnings part 1

### LINKED ISSUE #27: Replace deprecated isSupportsSelection()
When running `mvn verify`, I get the following warning:

```
[WARNING] [...]/openhtmltopdf-pdfbox/src/main/java/com/openhtmltopdf/pdfboxout/PdfBoxOutputDevice.java:[184,13] isSupportsSelection() in com.openhtmltopdf.extend.OutputDevice has been deprecated
[WARNING] [...]/openhtmltopdf-pdfbox/src/main/java/com/openhtmltopdf/pdfboxout/PdfBoxFastOutputDevice.java:[1057,20] isSupportsSelection() in com.openhtmltopdf.extend.OutputDevice has been deprecated
```

There are only four occurrences in total:

openhtmltopdf-core/src/main/java/com/openhtmltopdf/extend/OutputDevice.java:
```java
    
    @Deprecated
    public boolean isSupportsSelection();
    
    public boolean isSupportsCMYKColors();
```
openhtmltopdf-java2d/src/main/java/com/openhtmltopdf/java2d/Java2DOutputDevice.java:
```java
    @Deprecated
    @Override
    public boolean isSupportsSelection() {
        return false;
    }
```

openhtmltopdf-pdfbox/src/main/java/com/openhtmltopdf/pdfboxout/PdfBoxFastOutputDevice.java:
```java

   @Override
    public boolean isSupportsSelection() {
        return false;
    }
```

openhtmltopdf-pdfbox/src/main/java/com/openhtmltopdf/pdfboxout/PdfBoxOutputDevice.java:
```java

    @Override
    boolean isSupportsSelection();

    @Override
```

To me it seems like one can just remove the code.

### LINKED ISSUE #28: Switch to javadoc doclint option
When running `mvn verify`, I get the following warning:

```
[WARNING] Parameter 'additionalparam' is unknown for plugin 'maven-javadoc-plugin:3.2.0:jar (attach-javadocs)'
```

See also:
- https://stackoverflow.com/questions/52547306/maven-javadoc-plugin-not-accepting-additionalparam-xdoclintnone-additionalpa
- https://stackoverflow.com/questions/15886209/maven-is-not-working-in-java-8-when-javadoc-tags-are-incomplete
- https://maven.apache.org/plugins/maven-javadoc-plugin/javadoc-mojo.html#doclint

I will provide a PR to fix this.

### PR DESCRIPTION
**Pull request by XSpielinbox**
closes #27 
closes #28 
Remove license links with unencrypted protocol

### CODE REVIEW

File: openhtmltopdf-core/src/main/java/com/openhtmltopdf/extend/OutputDevice.java [hunk 1]
```diff
@@ -87,9 +87,6 @@ default public void drawLinearGradient(FSLinearGradient backgroundLinearGradient
     public Object getRenderingHint(Key key);
     public void setRenderingHint(Key key, Object value);
     
-    @Deprecated
-    public boolean isSupportsSelection();
-
```
Comment (siegelzc) [inline openhtmltopdf-core/src/main/java/com/openhtmltopdf/extend/OutputDevice.java:92]: Are we sure this isn't used anywhere?

File: pom.xml [hunk 2]
```diff
@@ -109,15 +109,6 @@
...
     </profile>
-    <profile>
-      <id>doclint-java8-disable</id>
-      <activation>
-        <jdk>[1.8,)</jdk>
-      </activation>
-      <properties>
-        <javadoc.opts>-Xdoclint:none</javadoc.opts>
-      </properties>
-    </profile>
```
[the remark this answers is not in the document]
Comment (siegelzc) [reply pom.xml:120]: Thanks for the explanation

File: LICENSE-LGPL-3.txt [hunk 3]
```diff
@@ -1,7 +1,7 @@
                    GNU LESSER GENERAL PUBLIC LICENSE
                        Version 3, 29 June 2007
 
- Copyright (C) 2007 Free Software Foundation, Inc. <http://fsf.org/>
```
Comment (madsop-nav) [inline LICENSE-LGPL-3.txt:4]: I was for a minute sceptical to this change, because of changing in a license file, but https://www.gnu.org/licenses/lgpl-3.0.en.html has the same, so it's fine.

**Review by madsop-nav — APPROVED** [review]

**Review by siegelzc — APPROVED** [review]
